version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:latest
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 7070:8080
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
  breedbase_db:
    image: breedbase/pg:latest
    container_name: breedbase_db
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
    name: bb_postgres