version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:dev
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 7080:8080
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ../sgn
        target: /home/production/cxgn/sgn
      - type: bind
        source: ../archive
        target: /home/production/archive
      - type: bind
        source: ../skins
        target: /home/production/cxgn/skins
    environment:
      MODE: 'DEVELOPMENT'
  breedbase_db:
    image: breedbase/pg:latest
    container_name: breedbase_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
    name: bb_postgres
