version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:v0.17
    depends_on:
      - breedbase_db
    container_name: breedbase_web

  breedbase_db:
    image: breedbase/pg:11
    container_name: breedbase_db
