version: "3.7"

services:
  breedbase:
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ./entrypoint.sh
        target: /entrypoint.sh
      - archive:/home/production/archive
      - tmp:/home/production/tmp
      - cache:/home/production/cache
      - cluster:/home/production/cluster
      - blast:/home/production/blast
      - images:/home/production/images
    ports:
      - 7080:8080
      - 25:25
    image: breedbase/breedbase:v0.19
    depends_on:
      - breedbase_db
    container_name: breedbase_web

  breedbase_db:
    volumes:
      - dbdata:/var/lib/postgresql/data
    image: postgres:12.6
    container_name: breedbase_db
    environment:
      POSTGRES_DB: breedbase
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres -d $${POSTGRES_DB} || exit 1"
      interval: 10s

volumes:
  archive:
  tmp:
  cache:
  cluster:
  blast:
  images:
  dbdata:
