version: "3.7"

services:
  breedbase:
    ports:
      - 7080:8080
      - 25:25
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ./repos
        target: /home/production/cxgn
      - archive:/home/production/archive
      - tmp:/home/production/tmp
      - cache:/home/production/cache
      - cluster:/home/production/cluster
      - blast:/home/production/blast
      - images:/home/production/images
    environment:
      MODE: 'DEVELOPMENT'

  breedbase_db:
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
    name: bb_postgres
