version: "3.7"

services:
  breedbase:
    ports:
      - 7080:8080
      - 25:25
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ./repos
        target: /home/production/cxgn
      - type: volume
        source: archive
        target: /home/production/archive
      - type: volume
        source: tmp
        target: /home/production/tmp
      - type: volume
        source: cache
        target: /home/production/cache
      - type: volume
        source: cluster
        target: /home/production/cluster
      - type: volume
        source: blast
        target: /home/production/blast
      - type: volume
        source: images
        target: /home/production/images
    environment:
      MODE: 'DEVELOPMENT'

  breedbase_db:
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
    name: bb_postgres
