version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:latest
    depends_on:
      - breedbase_db
    container_name: breedbase_web

  breedbase_db:
    image: breedbase/pg:latest
    container_name: breedbase_db
