version: "3.7"

services:
  breedbase:
    environment:
      PGDATABASE: ${PGDATABASE:?}
      PGHOST: ${PGHOST:?}
      PGPASSWORD: ${PGPASSWORD:?}
      PGUSER: ${PGUSER:?}
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - webdata:/home/production/volume
    ports:
      - 7080:8080
      - 25:25
    image: breedbase/breedbase:v0.21
    depends_on:
      - breedbase_db
    container_name: breedbase_web

  breedbase_db:
    volumes:
      - dbdata:/var/lib/postgresql/data
    image: postgres:12.6
    container_name: breedbase_db
    environment:
      POSTGRES_DB: ${PGDATABASE:?}
      POSTGRES_PASSWORD: ${PGPASSWORD:?}
    healthcheck:
      test: "pg_isready -U postgres -d $${POSTGRES_DB} || exit 1"
      interval: 10s

volumes:
  webdata:
  dbdata:
