version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:v0.19
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 8080:8080
      - 25:25
    volumes:
      - volume:/home/production/volume
  breedbase_db:
    image: breedbase/breedbase_pg12.4:v0.5
    container_name: breedbase_db
    volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
   pgdata:
   volume:
