version: "3.7"

services:
  breedbase:
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
    ports:
      - 7080:8080
      - 25:25
    image: breedbase/breedbase:v0.19
    depends_on:
      - breedbase_db
    container_name: breedbase_web

  breedbase_db:
    image: breedbase/pg:11
    container_name: breedbase_db
