services:
  breedbase:
    environment:
      PGDATABASE: ${PGDATABASE:?}
      PGHOST: ${PGHOST:?}
      PGPASSWORD: ${PGPASSWORD:?}
      PGUSER: ${PGUSER:?}
    image: breedinginsight/breedbase:latest
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 7080:8080
      - 25:25
    volumes:
      - webdata:/home/production/volume
  breedbase_db:
    volumes:
      - dbdata:/var/lib/postgresql/data
    image: postgres:12.7
    container_name: breedbase_db
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: ${PGDATABASE:?}
      POSTGRES_PASSWORD: ${PGPASSWORD:?}
    healthcheck:
      test: "pg_isready -U postgres -d $${POSTGRES_DB} || exit 1"
      interval: 10s

volumes:
  webdata:
  dbdata:
